### ISSUE TITLE
Incorrect handling of files with dashes in the HTML reporter

### ISSUE THREAD

**Issue by slact** [to-kr/luacov-multiple#4]
Files with dashes in their names generate incorrect directory names that include the filename, and result in 404s when browsing the report HTML.

The issue is caused by an unescaped string.gsub() call in [html.lua:55](https://github.com/to-kr/luacov-multiple/blob/master/src/luacov/reporter/multiple/html.lua#L55)

I've submitted a PR with the fix

**Comment by to-kr** [comment]
Fixed in version v0.3 (published https://luarocks.org/modules/to-kr/luacov-multiple/0.3-1)
